
# ================================================================
#  docker-compose.yml — Développement local
#  Lance l'API + une base PostgreSQL locale
#  En production (Render), utiliser Neon directement (sans ce fichier)
# ================================================================

services:

  # ---- Base de données PostgreSQL locale ----
  postgres:
    image: postgres:15-alpine
    container_name: banking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: banking_adminer
    restart: unless-stopped
    ports:
      - "8180:8080"

  # ---- API Spring Boot ----
  banking-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankingdb
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      #SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      #SPRING_DATASOURCE_PASSWORD: postgres
      PORT: 8080
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
