# =============================================
#  Configuration principale
#  Les valeurs sont surchargees par les
#  variables d'environnement en production
# =============================================

spring.application.name=banking-api
server.port=${PORT:8080}

#spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bankingdb}
#spring.datasource.username=${DATABASE_USERNAME:postgres}
#spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.open-in-view=false

#-----postgresql local-----
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver



# Pool de connexions HikariCP (optimise pour Neon serverless)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.keepalive-time=60000

# --- JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- Swagger / OpenAPI ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

# --- Logs ---
logging.level.cm.edu.banking=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

# --- JWT ---
app.jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# --- Email SMTP ---
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

# Expediteur des emails
app.mail.from=${MAIL_FROM}
app.mail.from-name=${MAIL_USERNAME}
# URL de base pour les liens de verification
app.base-url=${APP_BASE_URL:http://localhost:8080}

# --- Pagination (defauts) ---
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
# ----- Sérialisation JSON ------------------------------------
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Africa/Douala

# ----- Initialisation Super Admin ----------------------------
app.superadmin.email=${SUPERADMIN_EMAIL:mezatiogeril@gmail.com}
app.superadmin.password=${SUPERADMIN_PASSWORD:Admin123}
